version: '2.4'

services:
  backend:
    build: .
    image: ccr.ccs.tencentyun.com/your-namespace/memao-backend:1.0.0
    env_file: .envlocal
    environment:
      - DB_URI=${DB_URI}
      - GUNICORN_CMD_ARGS=--workers=3 --bind=:5000 --timeout=120 --worker-class=gevent
    expose:
      - "5000"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5000/health"]
      interval: 30s
      timeout: 5s
      retries: 3
    depends_on:
      mysql:
        condition: service_healthy
      redis:
        condition: service_healthy
    networks:
      - backend
    restart: unless-stopped
    mem_limit: 700m
    cpus: 0.8  # 如果你不打算切换到 version 3，则保留

  mysql:
    image: mysql:8.0
    ports:
      - "4406:3306"
    env_file: .envlocal
    environment:
      - MYSQL_ROOT_PASSWORD=${DB_ROOT_PASSWORD}
      - MYSQL_USER=${DB_USER}
      - MYSQL_PASSWORD=${DB_PASSWORD}
      - MYSQL_DATABASE=${DB_NAME}
    command:
      --innodb_buffer_pool_size=256M
      --innodb_log_file_size=64M
      --max_connections=100
    volumes:
      - mysql_data:/var/lib/mysql
      - ./mysql/conf:/etc/mysql/conf.d
      - ./mysql/init:/docker-entrypoint-initdb.d
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 15s
      timeout: 5s
      retries: 5
    networks:
      - backend
    restart: unless-stopped
    mem_limit: 500m
    cpus: 0.6

  redis:
    image: redis:6-alpine
    command: redis-server --maxmemory 200mb --maxmemory-policy allkeys-lru
    volumes:
      - redis_data:/data
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 3s
      retries: 3
    networks:
      - backend
    restart: unless-stopped
    mem_limit: 250m
    cpus: 0.2

  nginx:
    image: nginx:1.21-alpine
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./nginx/certs:/etc/nginx/certs
      - /var/www/memao-frontend/html:/usr/share/nginx/html
    depends_on:
      - backend
    networks:
      - backend
      - frontend  # <-- 这里拼写必须对

volumes:
  mysql_data:
  redis_data:

networks:
  backend:
  frontend:
