"""Add token_amount, wallet_address, minted fields

Revision ID: 0ac6f7e27b79
Revises: 2e4fd83cc6e2
Create Date: 2025-09-21 14:29:18.858184

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0ac6f7e27b79'
down_revision = '2e4fd83cc6e2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('paypal_orders',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('order_id', sa.String(length=128), nullable=False),
    sa.Column('token_name', sa.String(length=64), nullable=False),
    sa.Column('symbol', sa.String(length=16), nullable=False),
    sa.Column('supply', sa.BigInteger(), nullable=False),
    sa.Column('token_amount', sa.BigInteger(), nullable=False),
    sa.Column('wallet_address', sa.String(length=128), nullable=True),
    sa.Column('contract_address', sa.String(length=128), nullable=True),
    sa.Column('minted', sa.Boolean(), nullable=True),
    sa.Column('amount', sa.Numeric(precision=18, scale=8), nullable=False),
    sa.Column('payment_status', sa.Enum('pending', 'paid', 'failed', name='paymentstatusenum'), nullable=True),
    sa.Column('deploy_status', sa.Enum('pending', 'success', 'failed', name='deploystatusenum'), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('order_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('paypal_orders')
    # ### end Alembic commands ###
