"""Add fields to WithdrawalHistory for processing

Revision ID: 18f5c90a3f5e
Revises: 0c87cbe98766
Create Date: 2025-06-15 17:35:56.080806

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '18f5c90a3f5e'
down_revision = '0c87cbe98766'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('withdrawal_history', schema=None) as batch_op:
        batch_op.add_column(sa.Column('processed_at', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('tx_hash', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('remarks', sa.Text(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('withdrawal_history', schema=None) as batch_op:
        batch_op.drop_column('remarks')
        batch_op.drop_column('tx_hash')
        batch_op.drop_column('processed_at')

    # ### end Alembic commands ###
