"""ming stop update the points history db

Revision ID: 1c6aa9325dfc
Revises: d9646b0d9136
Create Date: 2025-08-03 10:40:37.307731

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '1c6aa9325dfc'
down_revision = 'd9646b0d9136'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('checkin_history', schema=None) as batch_op:
        batch_op.alter_column('points_earned',
               existing_type=mysql.INTEGER(),
               type_=sa.Numeric(precision=36, scale=18),
               existing_nullable=True)

    with op.batch_alter_table('user_points_accounts', schema=None) as batch_op:
        batch_op.alter_column('total_points',
               existing_type=mysql.INTEGER(),
               type_=sa.Numeric(precision=36, scale=18),
               existing_nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_points_accounts', schema=None) as batch_op:
        batch_op.alter_column('total_points',
               existing_type=sa.Numeric(precision=36, scale=18),
               type_=mysql.INTEGER(),
               existing_nullable=False)

    with op.batch_alter_table('checkin_history', schema=None) as batch_op:
        batch_op.alter_column('points_earned',
               existing_type=sa.Numeric(precision=36, scale=18),
               type_=mysql.INTEGER(),
               existing_nullable=True)

    # ### end Alembic commands ###
