"""update the chekcin points

Revision ID: 29a47e6727f7
Revises: 1c6aa9325dfc
Create Date: 2025-08-03 12:20:10.532339

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '29a47e6727f7'
down_revision = '1c6aa9325dfc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('checkin_history', schema=None) as batch_op:
        batch_op.alter_column('points_earned',
               existing_type=mysql.DECIMAL(precision=36, scale=18),
               type_=sa.Integer(),
               existing_nullable=True)

    with op.batch_alter_table('points_history', schema=None) as batch_op:
        batch_op.alter_column('change_amount',
               existing_type=mysql.INTEGER(),
               type_=sa.Numeric(precision=36, scale=18),
               existing_nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('points_history', schema=None) as batch_op:
        batch_op.alter_column('change_amount',
               existing_type=sa.Numeric(precision=36, scale=18),
               type_=mysql.INTEGER(),
               existing_nullable=False)

    with op.batch_alter_table('checkin_history', schema=None) as batch_op:
        batch_op.alter_column('points_earned',
               existing_type=sa.Integer(),
               type_=mysql.DECIMAL(precision=36, scale=18),
               existing_nullable=True)

    # ### end Alembic commands ###
