"""update vip db model

Revision ID: 2e4fd83cc6e2
Revises: d9752bfa5457
Create Date: 2025-09-07 17:46:03.601629

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2e4fd83cc6e2'
down_revision = 'd9752bfa5457'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('vip_subscriptions', schema=None) as batch_op:
        batch_op.add_column(sa.Column('tx_hash', sa.String(length=66), nullable=True))
        batch_op.add_column(sa.Column('created_at', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('updated_at', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('vip_subscriptions', schema=None) as batch_op:
        batch_op.drop_column('updated_at')
        batch_op.drop_column('created_at')
        batch_op.drop_column('tx_hash')

    # ### end Alembic commands ###
