"""add social_accounts table

Revision ID: 328123afbe3a
Revises: 427e609d4bd9
Create Date: 2025-08-17 18:30:06.319319

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '328123afbe3a'
down_revision = '427e609d4bd9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('social_accounts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('wallet_user_id', sa.Integer(), nullable=False),
    sa.Column('provider', sa.String(length=32), nullable=False),
    sa.Column('social_id', sa.String(length=100), nullable=False),
    sa.Column('handle', sa.String(length=64), nullable=True),
    sa.Column('verified', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['wallet_user_id'], ['wallet_users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('provider', 'social_id', name='uix_provider_social_id'),
    sa.UniqueConstraint('wallet_user_id', 'provider', name='uix_wallet_provider')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('social_accounts')
    # ### end Alembic commands ###
