"""Change airdrop_amount to String

Revision ID: 402be89df705
Revises: 1e5caeaffc3a
Create Date: 2025-06-22 17:05:16.815799

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '402be89df705'
down_revision = '1e5caeaffc3a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('airdrop_config', schema=None) as batch_op:
        batch_op.alter_column('airdrop_amount',
               existing_type=mysql.BIGINT(),
               type_=sa.String(length=50),
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('airdrop_config', schema=None) as batch_op:
        batch_op.alter_column('airdrop_amount',
               existing_type=sa.String(length=50),
               type_=mysql.BIGINT(),
               existing_nullable=True)

    # ### end Alembic commands ###
