"""create eth_orders

Revision ID: 417be66ad08a
Revises: 729ac03d2557
Create Date: 2025-10-07 18:47:23.519896

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '417be66ad08a'
down_revision = '729ac03d2557'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('eth_orders',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('order_id', sa.String(length=64), nullable=False),
    sa.Column('token_address', sa.String(length=66), nullable=True),
    sa.Column('wallet_address', sa.String(length=66), nullable=True),
    sa.Column('tx_hash', sa.String(length=100), nullable=True),
    sa.Column('token_name', sa.String(length=200), nullable=True),
    sa.Column('symbol', sa.String(length=50), nullable=True),
    sa.Column('supply', sa.Text(), nullable=True),
    sa.Column('decimals', sa.Integer(), nullable=True),
    sa.Column('deploy_status', sa.String(length=20), nullable=False),
    sa.Column('payment_type', sa.String(length=20), nullable=True),
    sa.Column('amount', sa.Numeric(precision=38, scale=18), nullable=True),
    sa.Column('error', sa.Text(), nullable=True),
    sa.Column('meta', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('eth_orders', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_eth_orders_order_id'), ['order_id'], unique=True)
        batch_op.create_index(batch_op.f('ix_eth_orders_token_address'), ['token_address'], unique=False)
        batch_op.create_index(batch_op.f('ix_eth_orders_tx_hash'), ['tx_hash'], unique=False)
        batch_op.create_index(batch_op.f('ix_eth_orders_wallet_address'), ['wallet_address'], unique=False)

    with op.batch_alter_table('user_accounts', schema=None) as batch_op:
        batch_op.create_foreign_key(None, 'users', ['user_id'], ['id'])

    with op.batch_alter_table('wallet_users', schema=None) as batch_op:
        batch_op.drop_constraint('wallet_users_ibfk_1', type_='foreignkey')
        batch_op.create_foreign_key(None, 'users', ['user_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('wallet_users', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('wallet_users_ibfk_1', 'users', ['user_id'], ['id'], ondelete='CASCADE')

    with op.batch_alter_table('user_accounts', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')

    with op.batch_alter_table('eth_orders', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_eth_orders_wallet_address'))
        batch_op.drop_index(batch_op.f('ix_eth_orders_tx_hash'))
        batch_op.drop_index(batch_op.f('ix_eth_orders_token_address'))
        batch_op.drop_index(batch_op.f('ix_eth_orders_order_id'))

    op.drop_table('eth_orders')
    # ### end Alembic commands ###
