"""Add db nonce

Revision ID: 427e609d4bd9
Revises: 623e6395d018
Create Date: 2025-08-10 12:44:25.725684

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '427e609d4bd9'
down_revision = '623e6395d018'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_points_accounts', schema=None) as batch_op:
        batch_op.add_column(sa.Column('withdraw_nonce', sa.Integer(), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_points_accounts', schema=None) as batch_op:
        batch_op.drop_column('withdraw_nonce')

    # ### end Alembic commands ###
