"""add user_id to EthOrder

Revision ID: 4ece1b7ad193
Revises: 417be66ad08a
Create Date: 2025-10-09 20:41:04.474941

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4ece1b7ad193'
down_revision = '417be66ad08a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('eth_orders', schema=None) as batch_op:
        batch_op.add_column(sa.Column('user_id', sa.String(length=128), nullable=True))
        batch_op.create_index(batch_op.f('ix_eth_orders_user_id'), ['user_id'], unique=False)
        batch_op.create_foreign_key(None, 'users', ['user_id'], ['id'])

    with op.batch_alter_table('paypal_orders', schema=None) as batch_op:
        batch_op.add_column(sa.Column('user_id', sa.String(length=128), nullable=True))
        batch_op.create_foreign_key(None, 'users', ['user_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('paypal_orders', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('user_id')

    with op.batch_alter_table('eth_orders', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_index(batch_op.f('ix_eth_orders_user_id'))
        batch_op.drop_column('user_id')

    # ### end Alembic commands ###
