"""Add daily_weight and last_weight_update to WalletUser

Revision ID: 5468617047a0
Revises: f3197dff5f72
Create Date: 2025-08-01 21:15:50.462921

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5468617047a0'
down_revision = 'f3197dff5f72'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('wallet_users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('daily_weight', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('last_weight_update', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('wallet_users', schema=None) as batch_op:
        batch_op.drop_column('last_weight_update')
        batch_op.drop_column('daily_weight')

    # ### end Alembic commands ###
