"""Add distribution_type column to airdrop_config

Revision ID: 623e6395d018
Revises: d69372e8e5ed
Create Date: 2025-08-09 13:13:46.395796

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '623e6395d018'
down_revision = 'd69372e8e5ed'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('airdrop_config', schema=None) as batch_op:
        batch_op.add_column(sa.Column('distribution_type', sa.String(length=20), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('airdrop_config', schema=None) as batch_op:
        batch_op.drop_column('distribution_type')

    # ### end Alembic commands ###
