"""update activity

Revision ID: 929f522c67d6
Revises: 11bca6ac4a78
Create Date: 2025-07-27 13:45:33.425815

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '929f522c67d6'
down_revision = '11bca6ac4a78'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('mining_history',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('wallet_user_id', sa.Integer(), nullable=False),
    sa.Column('mined_at', sa.DateTime(), nullable=True),
    sa.Column('points_earned', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['wallet_user_id'], ['wallet_users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('points_history',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('wallet_user_id', sa.Integer(), nullable=False),
    sa.Column('change_type', sa.String(length=50), nullable=False),
    sa.Column('change_amount', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('description', sa.String(length=255), nullable=True),
    sa.ForeignKeyConstraint(['wallet_user_id'], ['wallet_users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('points_history')
    op.drop_table('mining_history')
    # ### end Alembic commands ###
