"""add is_distributed and config table

Revision ID: aa3ce7791cdf
Revises: 18f5c90a3f5e
Create Date: 2025-06-22 14:04:25.454043

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'aa3ce7791cdf'
down_revision = '18f5c90a3f5e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('airdrop_config',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('is_task_enabled', sa.Boolean(), nullable=True),
    sa.Column('batch_size', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('airdrop_addresses', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_distributed', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('distributed_at', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('airdrop_addresses', schema=None) as batch_op:
        batch_op.drop_column('distributed_at')
        batch_op.drop_column('is_distributed')

    op.drop_table('airdrop_config')
    # ### end Alembic commands ###
