"""delete token amount model

Revision ID: c4fb9a71927a
Revises: 0ac6f7e27b79
Create Date: 2025-09-27 13:18:58.686409

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'c4fb9a71927a'
down_revision = '0ac6f7e27b79'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('paypal_orders', schema=None) as batch_op:
        batch_op.drop_column('token_amount')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('paypal_orders', schema=None) as batch_op:
        batch_op.add_column(sa.Column('token_amount', mysql.BIGINT(), autoincrement=False, nullable=False))

    # ### end Alembic commands ###
