"""add mining models

Revision ID: caa96912505a
Revises: 5468617047a0
Create Date: 2025-08-02 15:40:35.731378

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'caa96912505a'
down_revision = '5468617047a0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('mining_history', schema=None) as batch_op:
        batch_op.add_column(sa.Column('end_time', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('weight_snapshot', sa.Float(), nullable=False))
        batch_op.add_column(sa.Column('is_settled', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('is_mining', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('mining_history', schema=None) as batch_op:
        batch_op.drop_column('is_mining')
        batch_op.drop_column('is_settled')
        batch_op.drop_column('weight_snapshot')
        batch_op.drop_column('end_time')

    # ### end Alembic commands ###
