"""Add invite_records table

Revision ID: d69372e8e5ed
Revises: 29a47e6727f7
Create Date: 2025-08-03 17:26:05.678399

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd69372e8e5ed'
down_revision = '29a47e6727f7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('invite_records',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('inviter_address', sa.String(length=66), nullable=False),
    sa.Column('invitee_address', sa.String(length=66), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('invite_records', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_invite_records_invitee_address'), ['invitee_address'], unique=True)
        batch_op.create_index(batch_op.f('ix_invite_records_inviter_address'), ['inviter_address'], unique=False)

    op.create_table('vip_subscriptions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('wallet_user_id', sa.Integer(), nullable=False),
    sa.Column('start_date', sa.DateTime(), nullable=False),
    sa.Column('end_date', sa.DateTime(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['wallet_user_id'], ['wallet_users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('vip_subscriptions')
    with op.batch_alter_table('invite_records', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_invite_records_inviter_address'))
        batch_op.drop_index(batch_op.f('ix_invite_records_invitee_address'))

    op.drop_table('invite_records')
    # ### end Alembic commands ###
