"""change points db type to str

Revision ID: d9646b0d9136
Revises: caa96912505a
Create Date: 2025-08-02 19:29:56.747691

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'd9646b0d9136'
down_revision = 'caa96912505a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('mining_history', schema=None) as batch_op:
        batch_op.alter_column('points_earned',
               existing_type=mysql.INTEGER(),
               type_=sa.String(length=64),
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('mining_history', schema=None) as batch_op:
        batch_op.alter_column('points_earned',
               existing_type=sa.String(length=64),
               type_=mysql.INTEGER(),
               existing_nullable=True)

    # ### end Alembic commands ###
