"""detect models

Revision ID: f3197dff5f72
Revises: 929f522c67d6
Create Date: 2025-07-27 14:12:24.533847

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'f3197dff5f72'
down_revision = '929f522c67d6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('points_history', schema=None) as batch_op:
        batch_op.alter_column('change_type',
               existing_type=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=50),
               type_=sa.String(length=60),
               existing_nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('points_history', schema=None) as batch_op:
        batch_op.alter_column('change_type',
               existing_type=sa.String(length=60),
               type_=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=50),
               existing_nullable=False)

    # ### end Alembic commands ###
